#!/usr/bin/env bash

web=10
db=50
lb=20

    echo $'\nKlantnaam:'
    read Klantnaam
    sleep 1
    cd /home/Vagrant/VM2/klanten
    if [! -d $Klantnaam ];
        then
            echo $'\nIs dit een Productie of Testomgeving? (Prod/test)'
            read TypeOmgeving
    
    if [[ "$TypeOmgeving" = test ]];
    then  
        cd $Klantnaam
        if [[ -d test ]];
        then
        echo "De opgegeven klant heeft al een testomgeving, verwijder deze eerst voor er een nieuwe wordt aangemaakt."
        else
        mkdir test
        cd test
        touch Vagrantfile
    echo "Vagrant.configure(\"2\") do |config|
            config.ssh.insert_key = false
            config.ssh.private_key_path = [\"/home/Vagrant/.ssh/id_rsa\",\"~/.vagrant.d/insecure_private_key\"]
            "
    >> Vagrantfile
    echo $'\nVagrantfile is aangemaakt in de testomgeving'
    touch inventory.ini
    echo "# Hoeveel nodes van klant: $Klantnaam" >> inventory.ini

    echo "Geef de netwerkreeks op bv: 192.168.50"
    read netwerkreeks

    echo "Hoeveel Webservers heeft $Klantnaam nodig?"
    read Hoeveelheidweb

    if ["$Hoeveelheidweb" -gt "0"]
    then
        echo "[webservers]" >> inventory.ini
        for ((w=1; w<="$Hoeveelheidweb"; w++))
            do
                web=$((web+1))
                echo "config.vm.define \"$Klantnaam-test-web$w\" do |web01_conf|
                web01_conf.vm.box = \"ubuntu/bionic64\"
                web01_conf.vm.hostname = \"$Klantnaam-test-web$w\"
                web01_conf.vm.network \"private_network\" , ip: \"$netwerkreeks.$web\" 
                web01_conf.vm.provision \"file\", source: \"~/.ssh/id_rsa.pub\", destination: \"~/.ssh/authorized_keys\"
                web01_conf.vm.provider \"virtualbox\" do |vb|
                vb.memory = "512"
                vb.gui= false
                vb.name= \"$Klantnaam-test-web$w\"
                end
            end
            " >> Vagrantfile
                echo "vagrant@$netwerkreeks.$web" >> inventory.ini
            done
    echo $'\nDe Webserver is toegevoegd'
        else "Er zijn geen webservers toegevoegd"
    fi

echo "Hoeveel Databases heeft $Klantnaam nodig?"
    read Hoeveelheiddb

    if ["$Hoeveelheiddb" -gt "0"]
    then
        echo "[databaseservers]">> inventory.ini
        
        for (( w=1; w<="$Hoeveelheiddb"; w++))
            do
                db=$((db+1))
                echo "config.vm.define \"$Klantnaam-test-db$w\" do |db01_conf|
                db01_conf.vm.box = \"ubuntu/bionic64\"
                db01_conf.vm.hostname = \"$Klantnaam-test-db$w\"
                db01_conf.vm.network \"private_network\" , ip: \"$netwerkreeks.$db\" 
                db01_conf.vm.provision \"file\", source: \"~/.ssh/id_rsa.pub\", destination: \"~/.ssh/authorized_keys\"
                db01_conf.vm.provider \"virtualbox\" do |vb|
                vb.memory = \"512\"
                vb.gui= false
                vb.name= \"$Klantnaam-test-db$w\"
                end
            end
            " >> Vagrantfile
            echo "vagrant@$netwerkreeks.$db" >> inventory.ini
            done
                echo $'\nDe Database server is toegevoegd'
        else
                echo "Er zijn geen Datbase servers toegevoegd"
    fi

echo "Hoeveel Loadbalancers heeft $Klantnaam nodig?"
    read Hoeveelheidlb 

    if [ "$Hoeveelheidlb" -gt "0"]
    then   
        echo "[loadbalancers]" >> inventory.ini

        for ((w=1; w<="$Hoeveelheidlb"; w++))
            do
                lb=$((lb+1))
                echo "config.vm.define \"$Klantnaam-test-lb$w\" do |lba01_conf|
                lba01_conf.vm.box = \"ubuntu/bionic64\"
                lba01_conf.vm.hostname = \"$Klantnaam-test-lb$w\"
                lba01_conf.vm.network \"private_network\" , ip: \"$netwerkreeks.$lb\" 
                lba01_conf.vm.provision \"file\", source: \"~/.ssh/id_rsa.pub\", destination: \"~/.ssh/authorized_keys\"
                lba01_conf.vm.provider \"virtualbox\" do |vb|
                vb.memory = \"512\"
                vb.gui= false
                vb.name= \"$Klantnaam-test-lb$w\"
                end
            end" >> Vagrantfile
            echo "vagrant@$netwerkreeks.$lb" >> inventory.ini
            done
                echo $'\nDe Loadbalance server is toegevoegd'
        else
                echo "Er zijn geen Loadbalance servers toegevoegd"
    fi
echo "end" >> Vagrantfile
    fi 
    fi

    if [[ "$TypeOmgeving" = prod ]];
        then
            if [[ -d prod ]];
            then
            echo "De opgegeven klant heeft al een productieomgeving, verwijder deze eerst voor er een nieuwe wordt aangemaakt."
            else
            mkdir /home/Vagrant/VM2/klanten/$Klantnaam/prod
            cd /home/Vagrant/VM2/klanten/$Klantnaam/prod
            touch Vagrantfile
                echo "Vagrant.configure(\"2\") do |config|
            config.ssh.insert_key = false
            config.ssh.private_key_path = [\"/home/Vagrant/.ssh/id_rsa\",\"~/.vagrant.d/insecure_private_key\"]
            "
            echo $'\nVagrantfile is aangemaakt in de productieomgeving'
    touch inventory.ini
    echo "# Hoeveel nodes van klant: $Klantnaam" >> inventory.ini

    echo "Geef de netwerkreeks op bv: 192.168.50"
    read netwerkreeks

    echo "Hoeveel Webservers heeft $Klantnaam nodig?"
    read Hoeveelheidweb

    if ["$Hoeveelheidweb" -gt "0"]
    then
        echo "[webservers]" >> inventory.ini
        for ((w=1; w<="$Hoeveelheidweb"; w++))
            do
                web=$((web+1))
                echo "config.vm.define \"$Klantnaam-prod-web$w\" do |web01_conf|
                web01_conf.vm.box = \"ubuntu/bionic64\"
                web01_conf.vm.hostname = \"$Klantnaam-prod-web$w\"
                web01_conf.vm.network \"private_network\" , ip: \"$netwerkreeks.$web\" 
                web01_conf.vm.provision \"file\", source: \"~/.ssh/id_rsa.pub\", destination: \"~/.ssh/authorized_keys\"
                web01_conf.vm.provider \"virtualbox\" do |vb|
                vb.memory = "512"
                vb.gui= false
                vb.name= \"$Klantnaam-prod-web$w\"
                end
            end
            " >> Vagrantfile
                echo "vagrant@$netwerkreeks.$web" >> inventory.ini
            done
    echo $'\nDe Webserver is toegevoegd'
        else "Er zijn geen webservers toegevoegd"
    fi

echo "Hoeveel Databases heeft $Klantnaam nodig?"
    read Hoeveelheiddb

    if ["$Hoeveelheiddb" -gt "0"]
    then
        echo "[databaseservers]">> inventory.ini
        
        for (( w=1; w<="$Hoeveelheiddb"; w++))
            do
                db=$((db+1))
                echo "config.vm.define \"$Klantnaam-prod-db$w\" do |db01_conf|
                db01_conf.vm.box = \"ubuntu/bionic64\"
                db01_conf.vm.hostname = \"$Klantnaam-prod-db$w\"
                db01_conf.vm.network \"private_network\" , ip: \"$netwerkreeks.$db\" 
                db01_conf.vm.provision \"file\", source: \"~/.ssh/id_rsa.pub\", destination: \"~/.ssh/authorized_keys\"
                db01_conf.vm.provider \"virtualbox\" do |vb|
                vb.memory = \"512\"
                vb.gui= false
                vb.name= \"$Klantnaam-prod-db$w\"
                end
            end
            " >> Vagrantfile
            echo "vagrant@$netwerkreeks.$db" >> inventory.ini
            done
                echo $'\nDe Database server is toegevoegd'
        else
                echo "Er zijn geen Datbase servers toegevoegd"
    fi

echo "Hoeveel Loadbalancers heeft $Klantnaam nodig?"
    read Hoeveelheidlb 

    if [ "$Hoeveelheidlb" -gt "0"]
    then   
        echo "[loadbalancers]" >> inventory.ini

        for ((w=1; w<="$Hoeveelheidlb"; w++))
            do
                lb=$((lb+1))
                echo "config.vm.define \"$Klantnaam-prod-lb$w\" do |lba01_conf|
                lba01_conf.vm.box = \"ubuntu/bionic64\"
                lba01_conf.vm.hostname = \"$Klantnaam-prod-lb$w\"
                lba01_conf.vm.network \"private_network\" , ip: \"$netwerkreeks.$lb\" 
                lba01_conf.vm.provision \"file\", source: \"~/.ssh/id_rsa.pub\", destination: \"~/.ssh/authorized_keys\"
                lba01_conf.vm.provider \"virtualbox\" do |vb|
                vb.memory = \"512\"
                vb.gui= false
                vb.name= \"$Klantnaam-prod-lb$w\"
                end
            end" >> Vagrantfile
            echo "vagrant@$netwerkreeks.$lb" >> inventory.ini
            done
                echo $'\nDe Loadbalance server is toegevoegd'
        else
                echo "Er zijn geen Loadbalance servers toegevoegd"
    fi
echo "end" >> Vagrantfile
    fi 
    fi
    fi
vagrant up

echo "Running playbook"
ansible-playbook /home/Vagrant/VM2/ansibleplaybooks/infra.yml