#!/usr/bin/env bash

web=100
db=102
lb=99

	echo $'\nKlantnaam:'
	read klantnaam
	cd klanten
	if [[ -d $klantnaam ]];
	  then
		echo $'\nProductie of testomgeving(prod/test)'
		read keuze
		
	if [[ "$keuze" = test ]];
	then
		cd $klantnaam
		if [[ -d test ]]; 
		then
		echo "Er is al een test locatie, verwijder oude voordat nieuwe in gebruik kan worden genomen aub"
		else
		mkdir test
		cd test
		touch Vagrantfile
	echo "Vagrant.configure(\"2\") do |config|" >> Vagrantfile
	echo $'\nVagrantfile is aangemaakt'
	touch ansible.cfg
	echo "[defaults]
host_key_checking = false
inventory = hosts" >> ansible.cfg
	touch hosts
	echo "# Nodes van de klant: $klantnaam" >> hosts
	

	echo "Netwerkreeks, bijvoorbeeld 192.168.1"
	read netwerk

	echo "Aantal webservers"
	read aantalweb

	if [ "$aantalweb" -gt "0" ]
	then
		echo "[webservers]" >> hosts
		cp /home/vagrant/vm2/playbooks/apache.yml /home/vagrant/vm2/klanten/$klantnaam/$keuze
		cp /home/vagrant/vm2/templates/index.php /home/vagrant/vm2/klanten/$klantnaam/$keuze
		for (( w=1; w<="$aantalweb"; w++ ))
	do
		web=$((web+1))
		echo "config.vm.define \"$klantnaam-test-web$w\" do |web|
			web.vm.box =  \"hashicorp/precise64\"
			web.vm.network \"private_network\" , ip: \"$netwerk.$web\"
			web.vm.provision \"file\", source: \"~/.ssh/id_rsa.pub\", destination: \"~/.ssh/authorized_keys\"
			web.vm.hostname = \"$klantnaam-web$w\"
			web.vm.provider \"virtualbox\" do |web|
			web.name = \"$klantnaam-test-web$w\"
			web.memory = "512"
			end
		end
		"  >> Vagrantfile
		echo "vagrant@$netwerk.$web" >> hosts
		done
			echo $'\nWebserver(s) zijn toegevoegd'
		else
			echo "Geen webservers toegevoegd"
		fi

	echo "Aantal database(s)"
        read aantaldb

        if [ "$aantaldb" -gt "0" ]
        then
				echo "[sql]" >> hosts
				cp /home/vagrant/vm2/playbooks/sql.yml /home/vagrant/vm2/klanten/$klantnaam/$keuze
				cp /home/vagrant/vm2/templates/test_dump.sql /home/vagrant/vm2/klanten/$klantnaam/$keuze
                for (( w=1; w<="$aantaldb"; w++ ))
        do
                db=$((db+1))
                echo "config.vm.define \"$klantnaam-test-db$w\" do |db|
                        db.vm.box =  \"hashicorp/precise64\"
                        db.vm.network \"private_network\" , ip: \"$netwerk.$db\"
                        db.vm.provision \"file\", source: \"~/.ssh/id_rsa.pub\", destination: \"~/.ssh/authorized_keys\"
                        db.vm.hostname = \"$klantnaam-db$w\"
                        db.vm.provider \"virtualbox\" do |db|
                        db.name = \"$klantnaam-test-db$w\"
                        db.memory = "512"
                        end
                end
                "  >> Vagrantfile
                echo "vagrant@$netwerk.$db" >> hosts
                        done
                        echo $'\nDatabase server(s) zijn toegevoegd'
                else
                        echo "Geen database servers toegevoegd"
                fi
		
	echo "Aantal loadbalancers:"
        read aantallb

        if [ "$aantallb" -gt "0" ]
        then
				echo "[loadbalancer]" >> hosts
				cp /home/vagrant/vm2/playbooks/haproxy.yml /home/vagrant/vm2/klanten/$klantnaam/$keuze
				cp /home/vagrant/vm2/templates/haproxy.cfg /home/vagrant/vm2/klanten/$klantnaam/$keuze
                for (( w=1; w<="$aantallb"; w++ ))
        do
                lb=$((lb+1))
                echo "config.vm.define \"$klantnaam-test-lb$w\" do |db|
                        db.vm.box =  \"hashicorp/precise64\"
                        db.vm.network \"private_network\" , ip: \"$netwerk.$lb\"
                        db.vm.provision \"file\", source: \"~/.ssh/id_rsa.pub\", destination: \"~/.ssh/authorized_keys\"
                        db.vm.hostname = \"$klantnaam-lb$w\"
                        db.vm.provider \"virtualbox\" do |db|
                        db.name = \"$klantnaam-lb$w\"
                        db.memory = "512"
                        end
                end
                "  >> Vagrantfile
                echo "vagrant@$netwerk.$lb" >> hosts
                        done
			echo $'\nLoadbalancer(s) is/zijn toegevoegd'
                else
                        echo "Geen loadbalancers toegevoegd"
                fi
echo "end" >> Vagrantfile
		fi
		fi
	if [[ "$keuze" = prod ]];
	 then
		if [[ -d prod ]]; 
		then
		echo "Er is al een productie locatie, verwijder oude voordat nieuwe in gebruik kan worden genomen aub"
		else
		mkdir /home/vagrant/vm2/klanten/$klantnaam/prod
		cd /home/vagrant/vm2/klanten/$klantnaam/prod
		touch Vagrantfile
			echo "Vagrant.configure(\"2\") do |config|" >> Vagrantfile
			echo $'\nVagrantfile is aangemaakt'
		touch ansible.cfg
	echo "[defaults]
host_key_checking = false
inventory = hosts" >> ansible.cfg
	touch hosts
	echo "# Nodes van de klant: $klantnaam" >> hosts
	

	echo "Netwerkreeks, bijvoorbeeld 192.168.1"
	read netwerk

	echo "Aantal webservers"
	read aantalweb

	if [ "$aantalweb" -gt "0" ]
	then
		echo "[webservers]" >> hosts
		cp /home/vagrant/vm2/playbooks/apache.yml /home/vagrant/vm2/klanten/$klantnaam/$keuze
		cp /home/vagrant/vm2/templates/index.php /home/vagrant/vm2/klanten/$klantnaam/$keuze
		for (( w=1; w<="$aantalweb"; w++ ))
	do
		web=$((web+1))
		echo "config.vm.define \"$klantnaam-prod-web$w\" do |web|
			web.vm.box =  \"hashicorp/precise64\"
			web.vm.network \"private_network\" , ip: \"$netwerk.$web\"
			web.vm.provision \"file\", source: \"~/.ssh/id_rsa.pub\", destination: \"~/.ssh/authorized_keys\"
			web.vm.hostname = \"$klantnaam-web$w\"
			web.vm.provider \"virtualbox\" do |web|
			web.name = \"$klantnaam-prod-web$w\"
			web.memory = "512"
			end
		end
		"  >> Vagrantfile
		echo "vagrant@$netwerk.$web" >> hosts
		done
			echo $'\nWebserver(s) zijn toegevoegd'
		else
			echo "Geen webservers toegevoegd"
		fi

	echo "Aantal database(s)"
        read aantaldb

        if [ "$aantaldb" -gt "0" ]
        then
				echo "[sql]" >> hosts
				cp /home/vagrant/vm2/playbooks/sql.yml /home/vagrant/vm2/klanten/$klantnaam/$keuze
				cp /home/vagrant/vm2/templates/test_dump.sql /home/vagrant/vm2/klanten/$klantnaam/$keuze
                for (( w=1; w<="$aantaldb"; w++ ))
        do
                db=$((db+1))
                echo "config.vm.define \"$klantnaam-prod-db$w\" do |db|
                        db.vm.box =  \"hashicorp/precise64\"
                        db.vm.network \"private_network\" , ip: \"$netwerk.$db\"
                        db.vm.provision \"file\", source: \"~/.ssh/id_rsa.pub\", destination: \"~/.ssh/authorized_keys\"
                        db.vm.hostname = \"$klantnaam-db$w\"
                        db.vm.provider \"virtualbox\" do |db|
                        db.name = \"$klantnaam-prod-db$w\"
                        db.memory = "512"
                        end
                end
                "  >> Vagrantfile
                echo "vagrant@$netwerk.$db" >> hosts
                        done
                        echo $'\nDatabase server(s) zijn toegevoegd'
                else
                        echo "Geen database servers toegevoegd"
                fi
		
	echo "Aantal loadbalancers:"
        read aantallb

        if [ "$aantallb" -gt "0" ]
        then
				echo "[loadbalancer]" >> hosts
				cp /home/vagrant/vm2/playbooks/haproxy.yml /home/vagrant/vm2/klanten/$klantnaam/$keuze
				cp /home/vagrant/vm2/templates/haproxy.cfg /home/vagrant/vm2/klanten/$klantnaam/$keuze
                for (( w=1; w<="$aantallb"; w++ ))
        do
                lb=$((lb+1))
                echo "config.vm.define \"$klantnaam-prod-lb$w\" do |db|
                        db.vm.box =  \"hashicorp/precise64\"
                        db.vm.network \"private_network\" , ip: \"$netwerk.$lb\"
                        db.vm.provision \"file\", source: \"~/.ssh/id_rsa.pub\", destination: \"~/.ssh/authorized_keys\"
                        db.vm.hostname = \"$klantnaam-lb$w\"
                        db.vm.provider \"virtualbox\" do |db|
                        db.name = \"$klantnaam-prod-lb$w\"
                        db.memory = "512"
                        end
                end
                "  >> Vagrantfile
                echo "vagrant@$netwerk.$lb" >> hosts
                        done
			echo $'\nLoadbalancer(s) is/zijn toegevoegd'
                else
                        echo "Geen loadbalancers toegevoegd"
                fi
echo "end" >> Vagrantfile
		
		fi
		fi
		else
	mkdir $klantnaam
	echo $'\nMap is aangemaakt'
	cd $klantnaam
	echo $'\nProductie of testomgeving(prod/test)'
		read keuze
	
	if [[ "$keuze" = test ]];
	then
		if [[ -d test ]]; 
		then
		echo "Er is al een test locatie, verwijder oude voordat nieuwe in gebruik kan worden genomen aub"
		else
		mkdir test
		cd test
		touch Vagrantfile
	echo "Vagrant.configure(\"2\") do |config|" >> Vagrantfile
	echo $'\nVagrantfile is aangemaakt'
	touch ansible.cfg
	echo "[defaults]
host_key_checking = false
inventory = hosts" >> ansible.cfg
	touch hosts
	echo "# Nodes van de klant: $klantnaam" >> hosts
	

	echo "Netwerkreeks, bijvoorbeeld 192.168.1"
	read netwerk

	echo "Aantal webservers"
	read aantalweb

	if [ "$aantalweb" -gt "0" ]
	then
		echo "[webservers]" >> hosts
		cp /home/vagrant/vm2/playbooks/apache.yml /home/vagrant/vm2/klanten/$klantnaam/$keuze
		cp /home/vagrant/vm2/templates/index.php /home/vagrant/vm2/klanten/$klantnaam/$keuze
		
		for (( w=1; w<="$aantalweb"; w++ ))
	do
		web=$((web+1))
		echo "config.vm.define \"$klantnaam-test-web$w\" do |web|
			web.vm.box =  \"hashicorp/precise64\"
			web.vm.network \"private_network\" , ip: \"$netwerk.$web\"
			web.vm.provision \"file\", source: \"~/.ssh/id_rsa.pub\", destination: \"~/.ssh/authorized_keys\"
			web.vm.hostname = \"$klantnaam-test-web$w\"
			web.vm.provider \"virtualbox\" do |web|
			web.name = \"$klantnaam-test-web$w\"
			web.memory = "512"
			end
		end
		"  >> Vagrantfile
		echo "vagrant@$netwerk.$web" >> hosts
		done
			echo $'\nWebserver(s) zijn toegevoegd'
		else
			echo "Geen webservers toegevoegd"
		fi

	echo "Aantal database(s)"
        read aantaldb

        if [ "$aantaldb" -gt "0" ]
        then
				echo "[sql]" >> hosts
				cp /home/vagrant/vm2/playbooks/sql.yml /home/vagrant/vm2/klanten/$klantnaam/$keuze
				cp /home/vagrant/vm2/templates/test_dump.sql /home/vagrant/vm2/klanten/$klantnaam/$keuze
                for (( w=1; w<="$aantaldb"; w++ ))
        do
                db=$((db+1))
                echo "config.vm.define \"$klantnaam-test-db$w\" do |db|
                        db.vm.box =  \"hashicorp/precise64\"
                        db.vm.network \"private_network\" , ip: \"$netwerk.$db\"
                        db.vm.provision \"file\", source: \"~/.ssh/id_rsa.pub\", destination: \"~/.ssh/authorized_keys\"
                        db.vm.hostname = \"$klantnaam-db$w\"
                        db.vm.provider \"virtualbox\" do |db|
                        db.name = \"$klantnaam-test-db$w\"
                        db.memory = "512"
                        end
                end
                "  >> Vagrantfile
                echo "vagrant@$netwerk.$db" >> hosts
                        done
                        echo $'\nDatabase server(s) zijn toegevoegd'
                else
                        echo "Geen database servers toegevoegd"
                fi
		
	echo "Aantal loadbalancers:"
        read aantallb

        if [ "$aantallb" -gt "0" ]
        then
				echo "[loadbalancer]" >> hosts
				cp /home/vagrant/vm2/playbooks/haproxy.yml /home/vagrant/vm2/klanten/$klantnaam/$keuze
				cp /home/vagrant/vm2/templates/haproxy.cfg /home/vagrant/vm2/klanten/$klantnaam/$keuze
                for (( w=1; w<="$aantallb"; w++ ))
        do
                lb=$((lb+1))
                echo "config.vm.define \"$klantnaam-test-lb$w\" do |db|
                        db.vm.box =  \"hashicorp/precise64\"
                        db.vm.network \"private_network\" , ip: \"$netwerk.$lb\"
                        db.vm.provision \"file\", source: \"~/.ssh/id_rsa.pub\", destination: \"~/.ssh/authorized_keys\"
                        db.vm.hostname = \"$klantnaam-lb$w\"
                        db.vm.provider \"virtualbox\" do |db|
                        db.name = \"$klantnaam-test-lb$w\"
                        db.memory = "512"
                        end
                end
                "  >> Vagrantfile
                echo "vagrant@$netwerk.$lb" >> hosts
                        done
			echo $'\nLoadbalancer(s) is/zijn toegevoegd'
                else
                        echo "Geen loadbalancers toegevoegd"
                fi
      
echo "end" >> Vagrantfile
		
		fi
		fi
	if [[ "$keuze" = prod ]];
	 then
		if [[ -d prod ]]; 
		then
		echo "Er is al een productie locatie, verwijder oude voordat nieuwe in gebruik kan worden genomen aub"
		else
		mkdir /home/vagrant/vm2/klanten/$klantnaam/prod
		cd /home/vagrant/vm2/klanten/$klantnaam/prod
		touch Vagrantfile
	echo "Vagrant.configure(\"2\") do |config|" >> Vagrantfile
	echo $'\nVagrantfile is aangemaakt'
	touch ansible.cfg
	echo "[defaults]
host_key_checking = false
inventory = hosts" >> ansible.cfg
	touch hosts
	echo "# Nodes van de klant: $klantnaam" >> hosts
	

	echo "Netwerkreeks, bijvoorbeeld 192.168.1"
	read netwerk

	echo "Aantal webservers"
	read aantalweb

	if [ "$aantalweb" -gt "0" ]
	then
		echo "[webservers]" >> hosts
		cp /home/vagrant/vm2/playbooks/apache.yml /home/vagrant/vm2/klanten/$klantnaam/$keuze
		cp /home/vagrant/vm2/templates/index.php /home/vagrant/vm2/klanten/$klantnaam/$keuze
				for (( w=1; w<="$aantalweb"; w++ ))
	do
		web=$((web+1))
		echo "config.vm.define \"$klantnaam-prod-web$w\" do |web|
			web.vm.box =  \"hashicorp/precise64\"
			web.vm.network \"private_network\" , ip: \"$netwerk.$web\"
			web.vm.provision \"file\", source: \"~/.ssh/id_rsa.pub\", destination: \"~/.ssh/authorized_keys\"
			web.vm.hostname = \"$klantnaam-web$w\"
			web.vm.provider \"virtualbox\" do |web|
			web.name = \"$klantnaam-prod-web$w\"
			web.memory = "512"
			end
		end
		"  >> Vagrantfile
		echo "vagrant@$netwerk.$web" >> hosts
		done
			echo $'\nWebserver(s) zijn toegevoegd'
		else
			echo "Geen webservers toegevoegd"
		fi

	echo "Aantal database(s)"
        read aantaldb

        if [ "$aantaldb" -gt "0" ]
        then
				echo "[sql]" >> hosts
				cp /home/vagrant/vm2/playbooks/sql.yml /home/vagrant/vm2/klanten/$klantnaam/$keuze
				cp /home/vagrant/vm2/templates/test_dump.sql /home/vagrant/vm2/klanten/$klantnaam/$keuze
                for (( w=1; w<="$aantaldb"; w++ ))
        do
                db=$((db+1))
                echo "config.vm.define \"$klantnaam-prod-db$w\" do |db|
                        db.vm.box =  \"hashicorp/precise64\"
                        db.vm.network \"private_network\" , ip: \"$netwerk.$db\"
                        db.vm.provision \"file\", source: \"~/.ssh/id_rsa.pub\", destination: \"~/.ssh/authorized_keys\"
                        db.vm.hostname = \"$klantnaam-db$w\"
                        db.vm.provider \"virtualbox\" do |db|
                        db.name = \"$klantnaam-prod-db$w\"
                        db.memory = "512"
                        end
                end
                "  >> Vagrantfile
                echo "vagrant@$netwerk.$db" >> hosts
                        done
                        echo $'\nDatabase server(s) zijn toegevoegd'
                else
                        echo "Geen database servers toegevoegd"
                fi
		
	echo "Aantal loadbalancers:"
        read aantallb

        if [ "$aantallb" -gt "0" ]
        then
				echo "[loadbalancer]" >> hosts
				cp /home/vagrant/vm2/playbooks/haproxy.yml /home/vagrant/vm2/klanten/$klantnaam/$keuze
				cp /home/vagrant/vm2/templates/haproxy.cfg /home/vagrant/vm2/klanten/$klantnaam/$keuze
                for (( w=1; w<="$aantallb"; w++ ))
        do
                lb=$((lb+1))
                echo "config.vm.define \"$klantnaam-prod-lb$w\" do |db|
                        db.vm.box =  \"hashicorp/precise64\"
                        db.vm.network \"private_network\" , ip: \"$netwerk.$lb\"
                        db.vm.provision \"file\", source: \"~/.ssh/id_rsa.pub\", destination: \"~/.ssh/authorized_keys\"
                        db.vm.hostname = \"$klantnaam-lb$w\"
                        db.vm.provider \"virtualbox\" do |db|
                        db.name = \"$klantnaam-prod-lb$w\"
                        db.memory = "512"
                        end
                end
                "  >> Vagrantfile
                echo "vagrant@$netwerk.$lb" >> hosts
                        done
			echo $'\nLoadbalancer(s) is/zijn toegevoegd'
                else
                        echo "Geen loadbalancers toegevoegd"
                fi
echo "end" >> Vagrantfile
fi
fi			
fi
vagrant up

if [ "$aantalweb" -gt "0" ]
	then
	sleep 15
	cd /home/vagrant/vm2/klanten/$klantnaam/$keuze
	ansible-playbook apache.yml
		else
			echo "Geen webservers toegevoegd"
		fi
		
if [ "$aantaldb" -gt "0" ]
	then
	cd /home/vagrant/vm2/klanten/$klantnaam/$keuze
	ansible-playbook sql.yml
		else
			echo "Geen database servers toegevoegd"
		fi
		
if [ "$aantallb" -gt "0" ]
	then
	cd /home/vagrant/vm2/klanten/$klantnaam/$keuze
	ansible-playbook haproxy.yml
		else
			echo "Geen loadbalancer servers toegevoegd"
		fi
