cluster = {
 'S1049160Web1' => { :ip => '192.168.2.101', :mem => 512 }, 
 'S1049160Web2' => { :ip => '192.168.2.102', :mem => 512 }, 
 'S1049160Lb1' => { :ip => '192.168.2.21', :mem => 512 }, 
 'S1049160Db1' => { :ip => '192.168.2.31', :mem => 512 }, 
 }
Vagrant.configure("2") do |config|

    cluster.each_with_index do |(hostname, info), index|
  
      config.vm.define hostname do |cfg|
        cfg.vm.provider :virtualbox do |vb, override|
          config.vm.box = "ubuntu/trusty64"
          override.vm.hostname = hostname
          override.vm.network "private_network", ip: "#{info[:ip]}"
          vb.name = hostname
          vb.customize ["modifyvm", :id, "--memory", info[:mem]]
        end
      end
    end
  end