---
- name: Copy HAproxy configuration
  template:
    src: /home/Vagrant/VM2/ansibleplaybooks/roles/lb/files/haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: 0644
    validate: haproxy -f %s -c -q
  notify: Restart haproxy
