Vagrant.configure("2") do |config|

  config.ssh.insert_key = false
  config.ssh.private_key_path = ["/home/Vagrant/.ssh/id_rsa","~/.vagrant.d/insecure_private_key"]

  #Create Webserver01
  config.vm.define "Testklant1-WEB01" do |web01_conf|
    web01_conf.vm.box = "ubuntu/bionic64"
    web01_conf.vm.hostname = "Testklant1-WEB01"
    web01_conf.vm.network "private_network" , ip:"192.168.50.11" 
    web01_conf.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
    web01_conf.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.gui= false
      vb.name= "Testklant1-WEB01"
    end
  end
  #Create Webserver02
  config.vm.define "Testklant1-WEB02" do |web02_conf|
    web02_conf.vm.box = "ubuntu/bionic64"
    web02_conf.vm.hostname = "Testklant1-WEB02"
    web02_conf.vm.network "private_network" , ip:"192.168.50.12" 
    web02_conf.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
    web02_conf.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.gui= false
      vb.name= "Testklant1-WEB02"
    end
  end

  #Create Loadbalancer01
  config.vm.define "Testklant1-LB01" do |lba01_conf|
    lba01_conf.vm.box = "ubuntu/bionic64"
    lba01_conf.vm.hostname = "Testklant1-LB01"
    lba01_conf.vm.network "private_network" , ip: "192.168.50.21" 
    lba01_conf.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
    lba01_conf.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.gui= false
      vb.name= "Testklant1-LB01"
    end
  end

  #Create Database01
  config.vm.define "Testklant1-DB01" do |db01_conf|
    db01_conf.vm.box = "ubuntu/bionic64"
    db01_conf.vm.hostname = "Testklant1-DB01"
    db01_conf.vm.network "private_network" , ip: "192.168.50.31" 
    db01_conf.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
    db01_conf.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.gui= false
      vb.name= "Testklant1-DB01"
    end
  end
end